import Head from "next/head";
import Components from "../components";
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Wuubi - Sosyal İçerik Ağı</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.wrapperMain}>
        <div className={styles.contentArea}>

        <Components.Typography variant="h2" color="#e8e8e8" sx={{pb:2}}>
          Öne Çıkan İçerikler
        </Components.Typography>

       <div className={styles.featuredContents}>
       <Components.FeaturedPosts/>
       </div>

        </div>
        <div className={styles.sideBar}>
          <Components.Sidebar />
        </div>
      </main>
    </>
  );
}
