import Head from "next/head";
import Components from "../components";
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Wuubi - Sosyal İçerik Ağı</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className={styles.test} sx={{backgroundColor:'red'}}>

   <Components.FeaturedPosts />

        </div>
      </main>
    </>
  );
}
